# Generated by Django 3.2.6 on 2021-09-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('points', models.IntegerField()),
                ('result_text', models.CharField(max_length=255)),
            ],
        ),
    ]
