# Generated by Django 4.0 on 2022-05-17 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_user', '0001_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscenario',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_user.user'),
        ),
        migrations.AddField(
            model_name='textblock',
            name='decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_block', to='app.decision'),
        ),
        migrations.AddField(
            model_name='textblock',
            name='simulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_block', to='app.simulation'),
        ),
        migrations.AddField(
            model_name='task',
            name='predecessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='user_scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app.userscenario'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='template_scenario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='simulation', to='app.templatescenario'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='simulation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_card', to='app.simulation'),
        ),
        migrations.AddField(
            model_name='member',
            name='skill_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to='app.skilltype'),
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='app.team'),
        ),
        migrations.AddField(
            model_name='managementgoal',
            name='template_scenario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='management_goal', to='app.templatescenario'),
        ),
        migrations.AddField(
            model_name='decision',
            name='template_scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='app.templatescenario'),
        ),
        migrations.AddField(
            model_name='answer',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app.action'),
        ),
        migrations.AddField(
            model_name='action',
            name='decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='app.decision'),
        ),
        migrations.AddField(
            model_name='action',
            name='simulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='app.simulation'),
        ),
    ]
