name: Backend

on:
  push:
    branches:
    - develop
    paths:
    - 'backend/**'
    - '.github/workflows/copyBackend.yaml'
    - '!backend/requirements.txt'
    # - 'deploy/*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Rollout backend
    strategy:
      max-parallel: 1

    steps:
    - uses: actions/checkout@v3
    - name: Check / set env Prod
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |  
            echo "DIR=PROD/" >> $GITHUB_ENV

    - name: Check / set env Dev
      if: ${{ github.ref == 'refs/heads/develop' }}
      run: |
            echo "DIR=DEV/" >> $GITHUB_ENV

    - name: Prepare Backend
      run: |
            sshpass -p "${{ secrets.SSH_PAS }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{secrets.SSH_HOST}} << EOF
            mkdir -p ${{ secrets.BASE_DIR_APP }}${{ env.DIR }}swd
            EOF

    - name: Copy Files
      run: |
            sshpass -p "${{ secrets.SSH_PAS }}" scp -r -o StrictHostKeyChecking=no ./backend/* ${{ secrets.SSH_USER }}@${{secrets.SSH_HOST}}:${{ secrets.BASE_DIR_APP }}${{ env.DIR }}swd

   - name: Release Backend && Restart
      run: |
            sshpass -p "${{ secrets.SSH_PAS }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{secrets.SSH_HOST}} << EOF
            ssh local <<-'EOF2'
                docker-compose -f ${{ secrets.BASE_DIR_OPS }}compose/app/app_compose.yaml down
            EOF2 \
            && cd ${{ secrets.BASE_DIR_APP }} \
            && rm -rf bak || echo "bak not found" \
            && mv prd bak || echo "prd not found" \
            && mv swd prd || echo "swd not found" \
            && ssh local <<-'EOF2'
                docker-compose -f ${{ secrets.BASE_DIR_OPS }}compose/app/app_compose.yaml up -d
            EOF2 \
            EOF